AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# 80 is exaggerated, but we still try to keep it as low as possible
Metrics/LineLength:
  Max: 90
